---
title: "MATH 4753 Lab 1"
author: "Andrew Douglass"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Tasks

## Task 1

```{r}
getwd()
```

## Task 2

```{r}
ddt <- read.csv("DDT.csv")
head(ddt)
```

## Task 3

```{r}
print("Qualitative variables include River and Species. Quantitative variables inlcude Mile, Length, Weight, and DDT")
totalSpecies <- length(unique(ddt$SPECIES))
print(paste(totalSpecies, "Species"))

with(ddt, ddt[SPECIES=="LMBASS" & WEIGHT>800,])
#library(dplyr)
#ddt %>% filter(SPECIES == LMBASS, WEIGHT > 800) 

with(ddt, ddt[RIVER=="SCM" & DDT>4.0,])
```

## Task 4

```{r}
print("Mean length of fish in ddt data frame: ")
library(dplyr)
ddt %>% summarize(mean_LENGTH = mean(LENGTH))
with(ddt, mean(LENGTH))

print("Standard Deviation: ")
sd(ddt$WEIGHT)

print("0, Weight should be on Y axis as its X vs Y")
print("1, because the last value would be 20 and 20/20 is 1")
```

## Task 5

```{r}
tableR = table(ddt$RIVER)
print(tableR)

barplot(tableR, col=1:4)

tableRwF = with(ddt, table(SPECIES, RIVER))
print(tableRwF)

barplot(tableRwF, col=1:10)
```

## Task 6

```{r}
tableFish = table(ddt$SPECIES)
pie(tableFish, col=1:10)

tableRiver = table(ddt$RIVER)
pie(tableRiver, col=1:10)
```

## Task 7

```{r}
print("DDT Boxplot")
with(ddt, boxplot(DDT, ylab = "DDT", col=1, notch=TRUE))

print("Weight Boxplot")
with(ddt, boxplot(WEIGHT, ylab = "WEIGHT", col=2, notch=TRUE))

print("Length Boxplot")
with(ddt, boxplot(LENGTH, ylab = "LENGTH", col=3, notch=TRUE))
```

## Task 8

```{r}
print("Length VS Weight given River")
coplot(LENGTH~WEIGHT|RIVER, data=ddt, col=1)

print("DDT VS Weight given Species")
coplot(DDT~WEIGHT|SPECIES, data=ddt, col=1)
```

## Task 9

```{r}
print("ggplot Boxplot")
library(ggplot2)
ggchart = ggplot(ddt, aes(x=SPECIES, y=WEIGHT))
ggchart = ggchart + geom_boxplot(aes(fill=RIVER)) + ggtitle("Andrew Douglass")
ggchart

print("ggplot Violin Plot")
ggVN = ggplot(ddt, aes(x=RIVER, y=LENGTH))
ggVN = ggVN + geom_violin(aes(fill=SPECIES)) + ggtitle("Andrew Douglass")
ggVN

print("ggplot Scatter Plot")
ggScat = ggplot(ddt, aes(x=WEIGHT, y=LENGTH))
ggScat = ggScat + geom_point(aes(color=SPECIES)) + ggtitle("Andrew Douglass")
ggScat
```


