---
title: "Lab 6: MATH 4753"
author: "Andrew Douglass"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: spacelab
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Tasks

## Task 1

```{r}
getwd()
```

## Task 2

```{r}
#Using layout to create a 2x2 grid of plots
layout(matrix(1:4, nr=2,nc=2))
layout.show(4)
#Plotting curves using means and standard deviations given.X limit will keep the curve similar throughout each plot.
curve(dnorm(x, mean=10,sd=4),xlim=c(10-3*4, 10+3*4))

curve(dnorm(x, mean=10,sd=2),xlim=c(10-3*2, 10+3*2))

curve(dnorm(x, mean=5,sd=10),xlim=c(5-3*10, 5+3*10))

curve(dnorm(x, mean=5,sd=.5),xlim=c(5-3*.5, 5+3*.5))

#Plot of Y ~ N(0,1), P(Y greater than equal to 2)
curve(dnorm(x, mean=0,sd=1),xlim=c(-3,3))
xcurve=seq(2,5,length=1000)
ycurve=dnorm(xcurve,mean=0,sd=1)

polygon(c(2,xcurve,5),c(0,ycurve,0),col="Red")
prob=pnorm(5,mean=0,sd=1)-pnorm(2,mean=0,sd=1)
prob=round(prob,4)
text(x=.35, y=.1, paste("Area = ", prob, sep=""))

#Plot of Y ~ N(4,2), P(1 <= Y < 5)
curve(dnorm(x, mean=4,sd=2),xlim=c(0,8))
xcurve=seq(1,5,length=1000)
ycurve=dnorm(xcurve,mean=4,sd=2)
polygon(c(1,xcurve,5),c(0,ycurve,0),col="Red")
prob=pnorm(5,mean=4,sd=2)-pnorm(1,mean=4,sd=2)
prob=round(prob,4)
text(x=3.4, y=.1, paste("Area = ", prob, sep=""))

#Plot of Y ~ N(10, 4), P(Y < 10)
curve(dnorm(x, mean=10,sd=4),xlim=c(0,20))
xcurve=seq(0,10,length=1000)
ycurve=dnorm(xcurve,mean=10,sd=4)

polygon(c(0,xcurve,10),c(0,ycurve,0),col="Red")
prob=pnorm(10,mean=10,sd=4)
prob=round(prob,4)
text(x=3, y=.075, paste("Area = ", prob, sep=""))

#Plot of Y ~ N(-2, .5), P(-3 < Y <= -2)
curve(dnorm(x, mean=-2,sd=.5),xlim=c(-4,0))
xcurve=seq(-3,-2,length=1000)
ycurve=dnorm(xcurve,mean=-2,sd=.5)

polygon(c(-3,xcurve,-2),c(0,ycurve,0),col="Red")
prob=pnorm(-2,mean=-2,sd=.5)-pnorm(-3,mean=-2,sd=.5)
prob=round(prob,4)
text(x=-3.3, y=.55, paste("Area = ", prob, sep=""))
```


## Task 3

```{r}
#Gamma distribution using dgamma() and pgamma()
#Shape = 1, scale = 1
curve(dgamma(x,shape=1,scale=1),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Gamma Density", main="Shape = 1, scale = 1")
text(x=1.2, y=1, paste("alpha = 1"))

#Shape = 3, scale = 1
curve(dgamma(x,shape=3,scale=1),xlim=c(0,10),ylim=c(0,1),add=TRUE,lwd=2, col="Blue")
text(x=2.5, y=.35, paste("alpha = 3"))

#Shape = 5, scale = 1
curve(dgamma(x,shape=5,scale=1),xlim=c(0,10),ylim=c(0,1),add=TRUE, col="Green",lwd=2)
text(x=4.5, y=.275, paste("alpha = 5"))

#Shape = 3, scale = 2, P(2 < Y < 5)
curve(dgamma(x,shape=3,scale=2),xlim=c(0,10),ylim=c(0,.3),col="Black",lwd=2, ylab="Gamma Density", main="Shape = 3, scale = 2, P(2 < Y < 5)")
xcurve=seq(2,5,length=1000)
ycurve=dgamma(xcurve,shape=3,scale=2)
polygon(c(2,xcurve,5),c(0,ycurve,0),col="Red")
prob=pgamma(5,shape=3,scale=2)-pgamma(2,shape=3,scale=2)
prob=round(prob,4)
text(x=3.5, y=.3, paste("P(2 < Y < 5) = ", prob, sep=""))

#Shape = 6, scale = 3, P( 1 <= Y <= 4)
curve(dgamma(x,shape=6,scale=3),xlim=c(0,30),ylim=c(0,.06),col="Black",lwd=2, ylab="Gamma Density", main="Shape = 6, scale = 3, P(1 <= Y <= 4)")
xcurve=seq(1,4,length=1000)
ycurve=dgamma(xcurve,shape=6,scale=3)
polygon(c(1,xcurve,4),c(0,ycurve,0),col="Red")
prob=pgamma(4,shape=6,scale=3)-pgamma(1,shape=6,scale=3)
prob=round(prob,4)
text(x=15, y=.02, paste("P(1 <= Y <= 4) = ", prob, sep=""))

#Shape = 2, scale = 4, P( 3 <= Y < 6)
curve(dgamma(x,shape=2,scale=4),xlim=c(0,30),ylim=c(0,.1),col="Black",lwd=2, ylab="Gamma Density", main="Shape = 2, scale = 4, P(3 <= Y < 6)")
xcurve=seq(3,6,length=1000)
ycurve=dgamma(xcurve,shape=2,scale=4)
polygon(c(3,xcurve,6),c(0,ycurve,0),col="Red")
prob=pgamma(6,shape=2,scale=4)-pgamma(3,shape=2,scale=4)
prob=round(prob,4)
text(x=15, y=.08, paste("P(3 <= Y < 6) = ", prob, sep=""))
```

## Task 4

```{r}
#Chi-Square distribution shape = v/2, scale = 2
#Using layout() and breaking up graphical interface for 4 squares to plot
layout(matrix(1:4, nr=2,nc=2))
#Y ~ Chi-Square(df = 1)
curve(dchisq(x,df=1),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Chi-Square Density", main="df = 1")
#Y ~ Chi-Square(df = 2)
curve(dchisq(x,df=2),xlim=c(0,10),ylim=c(0,1),col="Blue",lwd=2, ylab="Chi-Square Density", main="df = 2")
#Y ~ Chi-Square(df = 4)
curve(dchisq(x,df=4),xlim=c(0,10),ylim=c(0,1),col="Green",lwd=2, ylab="Chi-Square Density", main="df = 4")
#Y ~ Chi-Square(df = 20)
curve(dchisq(x,df=20),xlim=c(0,50),ylim=c(0,.075),col="Black",lwd=2, ylab="Chi-Square Density", main="df = 20")

#Plotting the following Chi-Square distributions with probabilities
#Y ~ Chi-Square(df = 2), P(2 <= Y <= 4)
curve(dchisq(x,df=2),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Chi-Square Density", main="df = 2, P(2 <= Y <= 4)")
xcurve=seq(2,4,length=1000)
ycurve=dchisq(xcurve,df=2)
polygon(c(2,xcurve,4),c(0,ycurve,0),col="Red")
prob=round(pchisq(4,df=2)-pchisq(2,df=2),4)
text(x=4, y=.5, paste("P(2 <= Y <= 4) = ", prob, sep=""))

#Y ~ Chi-Square(df = 3), P(3 <= Y <= 5)
curve(dchisq(x,df=3),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Chi-Square Density", main="df = 3, P(3 <= Y <= 5)")
xcurve=seq(3,5,length=1000)
ycurve=dchisq(xcurve,df=3)
polygon(c(3,xcurve,5),c(0,ycurve,0),col="Red")
prob=round(pchisq(5,df=3)-pchisq(3,df=3),4)
text(x=4, y=.5, paste("P(3 <= Y <= 5) = ", prob, sep=""))

#Y ~ Chi-Square(df = 20), P(10 < Y <= 21)
curve(dchisq(x,df=20),xlim=c(0,50),ylim=c(0,.075),col="Red",lwd=2, ylab="Chi-Square Density", main="df = 20, P(10 < Y <= 21)")
xcurve=seq(10,21,length=1000)
ycurve=dchisq(xcurve,df=20)
polygon(c(10,xcurve,21),c(0,ycurve,0),col="Red")
prob=round(pchisq(21,df=20)-pchisq(10,df=20),4)
text(x=30, y=.05, paste("P(10 < Y <= 21) = ", prob, sep=""))

```

## Task 5

```{r}
#Weibull distribution using dweibull() and pweibull(). Making four plots using layout().
layout(matrix(1:4, nr=2,nc=2))
#Use any shape and scale
curve(dweibull(x,shape=1,scale=1),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Weibull Density", main="Shape = 1, scale = 1")
#using shape = 2, scale = 1
curve(dweibull(x,shape=2,scale=1),xlim=c(0,10),ylim=c(0,1),col="Blue",lwd=2, ylab="Weibull Density", main="Shape = 2, scale = 1")
#using shape = 3, scale = 2
curve(dweibull(x,shape=3,scale=2),xlim=c(0,10),ylim=c(0,1),col="Green",lwd=2, ylab="Weibull Density", main="Shape = 3, scale = 2")
#using shape = 4, scale = 3
curve(dweibull(x,shape=4,scale=3),xlim=c(0,10),ylim=c(0,1),col="Black",lwd=2, ylab="Weibull Density", main="Shape = 4, scale = 3")

#Now using probabilities for weibull
#Shape = 1, scale = 1, P(1 <= Y <= 3)
curve(dweibull(x,shape=1,scale=1),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Weibull Density", main="Shape = 1, scale = 1, P(1 <= Y <= 3)")
xcurve=seq(1,3,length=1000)
ycurve=dweibull(xcurve,shape=1,scale=1)
polygon(c(1,xcurve,3),c(0,ycurve,0),col="Red")
prob=pweibull(3,shape=1,scale=1)-pweibull(1,shape=1,scale=1)
prob=round(prob,4)
text(x=4, y=.5, paste("P(1 <= Y <= 3) = ", prob, sep=""))

#Shape = 2, scale = 1, P(2 <= Y <= 4)
curve(dweibull(x,shape=2,scale=1),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Weibull Density", main="Shape = 2, scale = 1, P(2 <= Y <= 4)")
xcurve=seq(2,4,length=1000)
ycurve=dweibull(xcurve,shape=2,scale=1)
polygon(c(2,xcurve,4),c(0,ycurve,0),col="Red")
prob=pweibull(4,shape=2,scale=1)-pweibull(2,shape=2,scale=1)
prob=round(prob,4)
text(x=4, y=.5, paste("P(2 <= Y <= 4) = ", prob, sep=""))

#Shape = 3, scale = 2, P(3 <= Y <= 4)
curve(dweibull(x,shape=3,scale=2),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Weibull Density", main="Shape = 3, scale = 2, P(3 <= Y <= 4)")
xcurve=seq(3,4,length=1000)
ycurve=dweibull(xcurve,shape=3,scale=2)
polygon(c(3,xcurve,4),c(0,ycurve,0),col="Red")
prob=pweibull(4,shape=3,scale=2)-pweibull(3,shape=3,scale=2)
prob=round(prob,4)
text(x=4, y=.5, paste("P(3 <= Y <= 4) = ", prob, sep=""))

```

## Task 6

```{r}
#Beta distribution 0 <= x <= 1 using dbeta() and pbeta(). Using task 5 layout.
layout(matrix(1:4, nr=2,nc=2))
#Shape1 = 1, Shape2 = 1
curve(dbeta(x,shape1=1,shape2=1),xlim=c(0,1),ylim=c(0,2),col="Red",lwd=2, ylab="Beta Density", main="Shape1 = 1, Shape2 = 1")
#Shape1 = 2, Shape2 = 1
curve(dbeta(x,shape1=2,shape2=1),xlim=c(0,1),ylim=c(0,2),col="Blue",lwd=2, ylab="Beta Density", main="Shape1 = 2, Shape2 = 1")
#Shape1 = 3, Shape2 = 2
curve(dbeta(x,shape1=3,shape2=2),xlim=c(0,1),ylim=c(0,2),col="Green",lwd=2, ylab="Beta Density", main="Shape1 = 3, Shape2 = 2")
#Shape1 = 4, Shape2 = 3
curve(dbeta(x,shape1=4,shape2=3),xlim=c(0,1),ylim=c(0,2),col="Black",lwd=2, ylab="Beta Density", main="Shape1 = 4, Shape2 = 3")

#Now using probabilities for beta
#Shape1 = 1, Shape2 = 1, P(0 <= Y <= 3)
curve(dbeta(x,shape1=1,shape2=1),xlim=c(0,1),ylim=c(0,2),col="Red",lwd=2, ylab="Beta Density", main="Shape1 = 1, Shape2 = 1, P(0 <= Y <= 3)")
xcurve=seq(0,3,length=1000)
ycurve=dbeta(xcurve,shape1=1,shape2=1)
polygon(c(0,xcurve,3),c(0,ycurve,0),col="Red")
prob=pbeta(3,shape1=1,shape2=1)-pbeta(0,shape1=1,shape2=1)
prob=round(prob,4)
text(x=.5, y=1.5, paste("P(0 <= Y <= 3) = ", prob, sep=""))

#Shape1 = 2, Shape2 = 1, P(0 <= Y <= 1)
curve(dbeta(x,shape1=2,shape2=1),xlim=c(0,1),ylim=c(0,2),col="Red",lwd=2, ylab="Beta Density", main="Shape1 = 2, Shape2 = 1, P(0 <= Y <= 1)")
xcurve=seq(0,1,length=1000)
ycurve=dbeta(xcurve,shape1=2,shape2=1)
polygon(c(0,xcurve,1),c(0,ycurve,0),col="Red")
prob=pbeta(1,shape1=2,shape2=1)-pbeta(0,shape1=2,shape2=1)
prob=round(prob,4)
text(x=.5, y=1.5, paste("P(0 <= Y <= 1) = ", prob, sep=""))

#Shape1 = 4, Shape2 = 8, P(3 <= Y <= 5)
curve(dbeta(x,shape1=4,shape2=8),xlim=c(0,1),ylim=c(0,2),col="Red",lwd=2, ylab="Beta Density", main="Shape1 = 4, Shape2 = 8, P(3 <= Y <= 5)")
xcurve=seq(3,5,length=1000)
ycurve=dbeta(xcurve,shape1=4,shape2=8)
polygon(c(3,xcurve,5),c(0,ycurve,0),col="Red")
prob=pbeta(5,shape1=4,shape2=8)-pbeta(3,shape1=4,shape2=8)
prob=round(prob,4)
text(x=.5, y=1.5, paste("P(3 <= Y <= 5) = ", prob, sep=""))

```

## Task 7

```{r}
#In form (mu, sigma, a)
FALL24DOUG0060::myncurve(10,5,6)

#Testing outputs:

cat("
==> devtools::test()

ℹ Testing FALL24DOUG0060
✔ | F W  S  OK | Context
✔ |          3 | myncurve                                                           

══ Results ═════════════════════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 3 ]")
```



